name: Nightly Build
'on':
  schedule:
  - cron: 0 7 * * *
  push:
    tags:
    - nightly
  workflow_call:
    inputs:
      is_PR:
        default: false
        type: boolean
        description: If a Pull Request has triggered it.
      PR_NUMBER:
        required: true
        type: number
        description: The Pull Request that triggered this workflow
      skip_tagging_and_releases:
        required: false
        default: true
        type: boolean
        description: Skips Tagging & releases, since workflow_call isn't available
          for github.event_name, default is true
    outputs:
      job_result:
        description: Build job result
        value: ${{ jobs.build.result }}
  workflow_dispatch:
    inputs:
      skip_tagging_and_releases:
        required: false
        default: true
        type: boolean
        description: Skips Tagging & releases, since workflow_call isn't available
          for github.event_name, default is true
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.ref_name == 'main'
    && github.sha || 'anysha' }}-${{ inputs.is_PR && 'is_PR' || 'not_PR'}}
  cancel-in-progress: true
permissions:
  contents: read
env:
  STORE_FILE_PATH: /tmp/app-debug.keystore
  BUILD_JSON_PATH: build.json
  VERSION_LABEL: ${{ (inputs.is_PR && 'pr') || 'nightly' }}
  DISCORD_RELEASE_NOTIFIER_ENABLED: 'true'
jobs:
  build:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    if: github.repository_owner == 'playground-nils'
    permissions:
      contents: write
      pull-requests: write
    outputs:
      release_output_url: ${{ steps.release.outputs.url }}
      updated_version: ${{ steps.update-version.outputs.UPDATED_VERSION}}
      RELEASE_NOTES: ${{ env.RELEASE_NOTES }}
    steps:
    - name: Fast Fail if secrets are missing
      if: ${{ env.KEYSTORE_CONTENT == '' || env.BUILD_JSON_CONTENT == '' }}
      env:
        KEYSTORE_CONTENT: ${{ secrets.KEYSTORE_CONTENT }}
        BUILD_JSON_CONTENT: ${{ secrets.BUILD_JSON_CONTENT }}
      run: 'echo "::error title=Missing Secrets::KEYSTORE_CONTENT or BUILD_JSON_CONTENT
        secrets are missing! Aborting workflow."

        exit 1

        '
    - name: Logging & summaries
      run: "echo \"::group::Logging\" \necho \"\U0001F3AF github trigger event name:\
        \ ${{ github.event_name }}\"\necho \"is_PR: ${{ inputs.is_PR }} \"\necho \"\
        PR_NUMBER: ${{ inputs.PR_NUMBER }}\" \necho \"env: STORE_FILE_PATH: ${{ env.STORE_FILE_PATH\
        \ }}\" \necho \"env: BUILD_JSON_PATH: ${{ env.BUILD_JSON_PATH }}\" \necho\
        \ \"env: VERSION_LABEL: ${{ env. VERSION_LABEL }}\"\necho \"github sha: ${{\
        \ github.sha }}\" \necho \"should not skip tags, releases: ${{ ! inputs.skip_tagging_and_releases\
        \ }} \" \necho \"::endgroup::\" \n\necho \"## \U0001F680 Build Type: ${{ env.VERSION_LABEL\
        \ }}\" >> $GITHUB_STEP_SUMMARY\necho \"is_PR: ${{ inputs.is_PR || 'NOT a PR'\
        \ }}\" >> $GITHUB_STEP_SUMMARY\necho \"PR_NUMBER: ${{ inputs.PR_NUMBER ||\
        \ 'not a PR' }}\" >> $GITHUB_STEP_SUMMARY\necho \"should not skip tags, releases:\
        \ ${{ ! inputs.skip_tagging_and_releases }}\" >> $GITHUB_STEP_SUMMARY    \
        \ \n"
    - name: Checkout Repository
      uses: actions/checkout@v6
      with:
        fetch-depth: 0
        persist-credentials: ${{ ! inputs.skip_tagging_and_releases }}
        ref: ${{ (inputs.is_PR && inputs.PR_NUMBER) && github.event.pull_request.head.sha
          || '' }}
    - name: Set up Java 21
      uses: actions/setup-java@v5
      with:
        distribution: temurin
        java-version: '21'
        cache: ${{ (!(inputs.is_PR && inputs.PR_NUMBER) && github.ref == 'refs/heads/main'
          && 'gradle') || '' }}
    - name: Set up Node.js
      uses: actions/setup-node@v6
      with:
        node-version: lts/*
        cache: ${{ (!(inputs.is_PR && inputs.PR_NUMBER) && github.ref == 'refs/heads/main'
          && 'npm') || '' }}
    - name: Add keystore and build.json from secrets
      run: 'echo "${{ secrets.KEYSTORE_CONTENT }}" | base64 -d > $STORE_FILE_PATH

        echo "${{ secrets.BUILD_JSON_CONTENT }}" | base64 -d > $BUILD_JSON_PATH

        echo "Keystore and build.json added successfully."

        '
    - name: Export Commit Hash & prev tag
      run: 'echo "GIT_COMMIT=$(git rev-parse HEAD)" >> $GITHUB_ENV

        echo "PREV_TAG=$(git describe --tags --abbrev=0 || git rev-list --max-parents=0
        HEAD)" >> $GITHUB_ENV

        '
    - name: Extract versionCode and version from config.xml
      id: extract_version
      run: 'if [ ! -f config.xml ]; then

        echo "config.xml not found!"

        exit 1

        fi

        VERSION_CODE=$(grep ''versionCode='' config.xml | sed -E ''s/.*versionCode="([0-9]+)".*/\1/'')

        VERSION=$(grep -oP ''version="\K[0-9.]+'' config.xml)

        echo "VERSION_CODE=$VERSION_CODE" >> $GITHUB_OUTPUT

        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

        echo "Extracted Version Code: $VERSION_CODE"

        echo "Extracted Version: $VERSION"

        '
    - name: Append Commit Hash to Version and Update config.xml
      id: update-version
      run: "SHORT_COMMIT_HASH=$(echo \"${{ env.GIT_COMMIT }}\" | cut -c 1-7)\nif ${{\
        \ inputs.is_PR  || false }}; then \n  PR_NUMBER=${{ inputs.PR_NUMBER }}\n\
        else\n  PR_NUMBER=\nfi\nUPDATED_VERSION=\"${{ steps.extract_version.outputs.VERSION\
        \ }}-${{ env.VERSION_LABEL }}.${PR_NUMBER:-$SHORT_COMMIT_HASH}\"\necho \"\
        Updated Version: $UPDATED_VERSION\"\n\n# Update config.xml with the new version\n\
        sed -i \"s/version=\\\"${{ steps.extract_version.outputs.VERSION }}\\\"/version=\\\
        \"$UPDATED_VERSION\\\"/g\" config.xml\necho \"Updated version in config.xml\"\
        \n# Output the updated version\necho \"UPDATED_VERSION=$UPDATED_VERSION\"\
        \ >> $GITHUB_ENV\necho \"UPDATED_VERSION=$UPDATED_VERSION\" >> $GITHUB_OUTPUT\
        \ \n"
    - name: Install Node.js Packages
      run: npm install
    - name: Install Cordova CLI
      run: npm install -g cordova
    - name: Run npm setup
      run: npm run setup
    - name: Run npm build paid dev apk
      run: 'node utils/storage_manager.mjs y

        npm run build paid dev apk

        mv platforms/android/app/build/outputs/apk/debug/app-debug.apk /tmp/app-debug-normal.apk

        echo "VERSION: $UPDATED_VERSION" >> $GITHUB_STEP_SUMMARY

        '
    - name: Upload APK Artifact
      uses: actions/upload-artifact@v7
      with:
        name: app-debug-${{ env.GIT_COMMIT }}
        path: /tmp/app-debug-normal.apk
    - name: Run npm build paid dev apk fdroid (for F-Droid)
      if: ${{ !inputs.is_PR }}
      run: 'node utils/storage_manager.mjs y

        npm run build paid dev apk fdroid

        mv platforms/android/app/build/outputs/apk/debug/app-debug.apk /tmp/app-debug-fdroid.apk

        '
    - name: Upload APK Artifact
      uses: actions/upload-artifact@v7
      if: ${{ !inputs.is_PR }}
      with:
        name: app-debug-fdroid-${{ env.GIT_COMMIT }}
        path: /tmp/app-debug-fdroid.apk
    - name: remove keystore and build.json
      run: 'rm $STORE_FILE_PATH $BUILD_JSON_PATH

        echo "Keystore and build.json removed successfully."

        '
    - name: Check Nightly Tag and Force Update
      if: ${{ ! inputs.skip_tagging_and_releases }}
      id: check-nightly-tag-force-update
      run: "# Check if the nightly tag exists and get the commit it points to\nif\
        \ git show-ref --quiet refs/tags/nightly; then\n  TAG_COMMIT=$(git rev-parse\
        \ nightly)\nelse\n  TAG_COMMIT=\"\"\nfi\n\n# If the current commit is the\
        \ same as the tag, skip updating the tag\nif [ \"$TAG_COMMIT\" != \"${{ env.GIT_COMMIT\
        \ }}\" ]; then\n  echo \"releaseRequired=true\" >> $GITHUB_ENV\n  # export\
        \ tag commit before updating for change logs comparing. \n  echo \"TAG_COMMIT=$TAG_COMMIT\"\
        \ >> $GITHUB_ENV \n\n  git config --global user.name 'GitHub Actions'\n  git\
        \ config --global user.email 'github-actions@github.com'\n  git tag -f nightly\n\
        \  git push origin nightly --force\nelse\n  echo \"Nightly tag already points\
        \ to this commit. Skipping update.\"\nfi\n"
    - name: Generate Release Notes (Experimental)
      if: ${{ success() && env.releaseRequired == 'true' }}
      id: gen-release-notes
      continue-on-error: true
      run: "RELEASE_NOTES=$(node utils/scripts/generate-release-notes.js ${{ github.repository_owner\
        \ }} Acode ${{ github.sha }} --format md --from-tag ${{ env.TAG_COMMIT }}\
        \ --important-only --quiet --changelog-only)\n{\n  echo \"RELEASE_NOTES<<EOF\"\
        \n  echo \"$RELEASE_NOTES\"\n  echo \"EOF\"\n} >> $GITHUB_ENV        \n"
      env:
        GITHUB_TOKEN: ${{ secrets.NIGHTLY_RELEASE_NOTES_GH_TOKEN }}
    - name: Release Nightly Version
      id: release
      if: ${{ ! inputs.skip_tagging_and_releases && steps.check-nightly-tag-force-update.outcome
        == 'success' && env.releaseRequired == 'true' && !inputs.is_PR }}
      uses: softprops/action-gh-release@v2
      with:
        prerelease: true
        name: ${{ env.UPDATED_VERSION }}
        tag_name: ${{ env.UPDATED_VERSION }}
        files: '/tmp/app-debug-normal.apk

          /tmp/app-debug-fdroid.apk

          '
        body: 'Automated Nightly (pre-release) Releases for Today


          [Compare Changes](https://github.com/${{ github.repository }}/compare/${{
          env.TAG_COMMIT }}...${{ github.sha }})


          ${{ env.RELEASE_NOTES }}

          '
    - name: Update Last Comment by bot (If ran in PR)
      if: inputs.is_PR
      uses: marocchino/sticky-pull-request-comment@v3
      with:
        hide_and_recreate: true
        hide_classify: OUTDATED
        header: on-demand-build-status
        message: 'Preview Release for this, has been built.


          [Click here to view that github actions build](https://github.com/${{ github.repository}}/actions/runs/${{
          github.run_id }})

          '
  community-release-notifier:
    needs: build
    if: ${{ github.repository_owner == 'playground-nils' && (contains(fromJSON('["push",
      "schedule"]'), github.event_name) || ! inputs.skip_tagging_and_releases) &&
      needs.build.outputs.release_output_url }}
    uses: Acode-Foundation/acode/.github/workflows/community-release-notifier.yml@main
    with:
      tag_name: ${{ needs.build.outputs.updated_version }}
      url: ${{ needs.build.outputs.release_output_url }}
      body: ${{ needs.build.outputs.RELEASE_NOTES }}
    secrets:
      DISCORD_WEBHOOK_RELEASE_NOTES: ${{ secrets.DISCORD_WEBHOOK_RELEASE_NOTES }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      TELEGRAM_MESSAGE_THREAD_ID: ${{ secrets.TELEGRAM_MESSAGE_THREAD_ID }}
