name: On Demand Preview Releases for PR
'on':
  pull_request_target:
    paths-ignore:
    - '!*.md'
    types:
    - labeled
    - synchronize
permissions:
  contents: write
  pull-requests: write
  issues: write
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.ref_name == 'main'
    && github.sha || 'anysha' }}
  cancel-in-progress: true
jobs:
  job_trigger:
    name: Trigger Preview Release (if conditions met)
    if: "github.event.pull_request.draft == false\n&& (github.repository_owner ==\
      \ 'playground-nils'\n&& (!contains(github.event.pull_request.labels.*.name,\
      \ 'DO NOT PREVIEW RELEASE') \n&& (contains(github.event.pull_request.labels.*.name,\
      \ 'Bypass check - PREVIEW RELEASE') \n|| contains(github.event.pull_request.labels.*.name,\
      \ 'CI: RUN ON-DEMAND PREVIEW RELEASES')))\n)\n"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v6
      with:
        clean: false
        fetch-depth: 0
        persist-credentials: false
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Remove Manually added PR Label
      if: 'contains(github.event.pull_request.labels.*.name, ''CI: RUN ON-DEMAND PREVIEW
        RELEASES'')

        '
      run: gh pr edit $PR --remove-label "$labels"
      env:
        PR: ${{ github.event.pull_request.number }}
        labels: 'CI: RUN ON-DEMAND PREVIEW RELEASES'
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Add comment to PR
      uses: marocchino/sticky-pull-request-comment@v3
      with:
        hide_and_recreate: true
        hide_classify: OUTDATED
        header: on-demand-build-status
        message: "\u2692\uFE0F Starting a workflow to build, Your On-Demand Preview\
          \ Release/build for ${{ github.event.pull_request.html_url || github.event.pull_request.url\
          \ }}.\n\nstatus: **\\`\U0001F7E1 in_progress\\`**\n\nKindly wait, this message\
          \ may be updated with success or failure status.\n\nFor Owners: Please [Click\
          \ here to view that github actions](https://github.com/${{ github.repository}}/actions/runs/${{\
          \ github.run_id }})/\n"
      env:
        PR: ${{ github.event.pull_request.number }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  trigger_builder:
    needs: job_trigger
    secrets: inherit
    uses: Acode-Foundation/acode/.github/workflows/nightly-build.yml@main
    with:
      is_PR: true
      PR_NUMBER: ${{ github.event.pull_request.number }}
      skip_tagging_and_releases: true
  update_Last_Comment:
    needs:
    - job_trigger
    - trigger_builder
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'playground-nils' && always() && contains(fromJSON('["failure","cancelled"]'),
      needs.trigger_builder.result) }}
    steps:
    - name: Update Last Comment by bot (if Workflow Triggering failed)
      uses: marocchino/sticky-pull-request-comment@v3
      with:
        hide_and_recreate: true
        hide_classify: OUTDATED
        header: on-demand-build-status
        message: "\U0001F534 (Workflow Trigger stopped), Your On-Demand Preview Release/build\
          \ for ${{ github.event.pull_request.html_url || github.event.pull_request.url\
          \ }}.\nstatus: **${{ needs.trigger_builder.result || 'failure'}}**     \
          \    \n\n---\nFor Owners: Please [Click here to view that github actions](https://github.com/${{\
          \ github.repository}}/actions/runs/${{ github.run_id }})\n"
